rules:
  'import/no-default-export': 2
  camelcase: 2
  'no-param-reassign': 2
  'prettier/prettier': 2
  'max-lines': [2, 200]
  'no-console': 2
  '@typescript-eslint/no-unused-vars': 2
  '@typescript-eslint/consistent-type-assertions':
    - error
    - assertionStyle: never
  '@typescript-eslint/no-explicit-any':
    - error
    - fixToUnknown: false
  'arrow-body-style': 2
  eqeqeq: 2

overrides:
  - files: ['*.ts', '*.tsx']
    rules:
      '@typescript-eslint/no-unsafe-call': 2
  
  - files: ['*.js']
    rules:
      '@typescript-eslint/no-var-requires': 0
      'no-undef': 0

extends:
  - prettier
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'

plugins:
  - prefer-arrow-functions
  - '@typescript-eslint'
  - prettier
  - import

env:
  node: true

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: 'module'
  project: 'tsconfig.json'
