group: example
languages:
  base: en
  other: ['fr', 'de']
namespaces:
  target: base.generated
  other: ['legal', 'base']
path: 'tests/todo/{{lang}}/{{namespace}}.json'
validation:
  mismatchedPlaceholders:
    - error.validation.required
